// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnluNmdCXVB4kXwb2kEeWdHi_UH84bguc',
    appId: '1:304612385908:web:37ea82f7fa815f148edd21',
    messagingSenderId: '304612385908',
    projectId: 'estacionamento-1',
    authDomain: 'estacionamento-1.firebaseapp.com',
    storageBucket: 'estacionamento-1.firebasestorage.app',
    measurementId: 'G-GHYLF3ECN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3R5HHdtcDag8lapC6yaEiQCNHQ7BEsUQ',
    appId: '1:304612385908:android:8182be14b050950b8edd21',
    messagingSenderId: '304612385908',
    projectId: 'estacionamento-1',
    storageBucket: 'estacionamento-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrbR26JcrmMMHFsfYZZLUC8jRhRSDofFg',
    appId: '1:304612385908:ios:e73f9e721ac7f0038edd21',
    messagingSenderId: '304612385908',
    projectId: 'estacionamento-1',
    storageBucket: 'estacionamento-1.firebasestorage.app',
    iosClientId: '304612385908-mv7cfa03mnmnubsc6ha4pknmtab8rt5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.vagacerta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrbR26JcrmMMHFsfYZZLUC8jRhRSDofFg',
    appId: '1:304612385908:ios:e73f9e721ac7f0038edd21',
    messagingSenderId: '304612385908',
    projectId: 'estacionamento-1',
    storageBucket: 'estacionamento-1.firebasestorage.app',
    iosClientId: '304612385908-mv7cfa03mnmnubsc6ha4pknmtab8rt5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.vagacerta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnluNmdCXVB4kXwb2kEeWdHi_UH84bguc',
    appId: '1:304612385908:web:37ea82f7fa815f148edd21',
    messagingSenderId: '304612385908',
    projectId: 'estacionamento-1',
    authDomain: 'estacionamento-1.firebaseapp.com',
    storageBucket: 'estacionamento-1.firebasestorage.app',
    measurementId: 'G-GHYLF3ECN0',
  );
}
